### ISSUE TITLE
Trigger error when mvt tile request fails

### ISSUE THREAD

**Issue by xavijam** [CartoDB/tangram.cartodb#18]
Related ticket: https://github.com/CartoDB/cartodb.js/issues/1717

When the user reaches its limits, mapnik vector tiles could be affected, so the idea is to warn CARTO.js about that problem and then it should trigger that error accordingly.

## Caveats

- We need to research if we could "render"/draw an error tile in the WebGL layer.

**Comment by rubenmoya** [comment]
Since we changed the error handling [in Tangram](https://github.com/CartoDB/tangram/pull/5/files#diff-06e3f25a9a00a1a8840d2720f9ab37e1R266) to load the tile no matter what, and windshaft is returning a `json` instead of a MVT (wip [here](https://github.com/CartoDB/Windshaft-cartodb/issues/782)) Tangram is throwing an `Uncaught (in promise) Error: Unimplemented type: 3` error when testing in staging, so I'm blocking this until windshaft returns a MVT

**Comment by rubenmoya** [comment]
Closed vía https://github.com/CartoDB/tangram/pull/5
